export const CATEGORY_LIST = [
  "general",
  "news",
  "videos",
  "images",
  "science",
  "it",
  "files",
  "social+media",
  "map",
  "music"
];

export const RECENCY_ALLOWED_LIST = ["day", "week", "month", "year"];

export const SEARX_DOMAINS = [
  "baresearch.org",
  "copp.gg",
  "darmarit.org",
  "etsi.me",
  "fairsuch.net",
  "nogoo.me",
  "northboot.xyz",
  "nyc1.sx.ggtyler.dev",
  "ooglester.com",
  "opnxng.com",
  "paulgo.io",
  "priv.au",
  "s.trung.fun",
  "search.blitzw.in",
  "search.charliewhiskey.net",
  "search.citw.lgbt",
  "search.darkness.services",
  "search.datura.network",
  "search.dotone.nl",
  "search.gcomm.ch",
  "search.hbubli.cc",
  "search.im-in.space",
  "search.incogniweb.net",
  "search.inetol.net",
  "search.leptons.xyz",
  "search.nadeko.net",
  "search.ngn.tf",
  "search.ononoki.org",
  "search.privacyredirect.com",
  "search.sapti.me",
  "search.rowie.at",
  "search.projectsegfau.lt",
  "search.tommy-tran.com",
  "searx.aleteoryx.me",
  "searx.ankha.ac",
  "searx.be",
  "searx.colbster937.dev",
  "searx.daetalytica.io",
  "searx.dresden.network",
  "searx.foss.family",
  "searx.hu",
  "searx.juancord.xyz",
  "searx.lunar.icu",
  "searx.mxchange.org",
  "searx.namejeff.xyz",
  "searx.oakleycord.dev",
  "searx.ro",
  "searx.sev.monster",
  "searx.thefloatinglab.world",
  "searx.tiekoetter.com",
  "searx.tuxcloud.net",
  "searx.work",
  "searx.zhenyapav.com",
  "searxng.hweeren.com",
  "searxng.online",
  "searxng.shreven.org",
  "searxng.site",
  "skyrimhater.com",
  "sx.ca.zorby.top",
  "sx.catgirl.cloud",
  "sx.thatxtreme.dev",
  "sx.zorby.top",
  "xo.wtf"
];



export const engines = {
  "general": [
    ["google", "The world's most popular web search engine."],
    ["bing", "Microsoft's web search engine for the general web."],
    ["brave", "Privacy-focused web search integrated with the Brave browser."],
    ["duckduckgo", "Privacy-oriented search engine that does not track users."],
    ["qwant", "European privacy-focused web search engine."],
    ["startpage", "Search engine that proxies Google results with enhanced privacy."],
    ["yahoo", "Web portal providing search, email, and news."],
    ["ask", "Question-answering oriented web search engine."],
    ["wikipedia", "Free, community-edited online encyclopedia."],
    ["wikidata", "Structured, collaborative knowledge base from Wikimedia."],
    ["wolframalpha", "Computational knowledge engine for factual queries and calculations."]
  ],
  "news": [
    ["duckduckgo news", "Aggregated news search powered by DuckDuckGo."],
    ["mojeek news", "News search vertical from the independent Mojeek engine."],
    ["bing news", "News aggregation and search from Microsoft Bing."],
    ["brave.news", "Privacy-focused news search from Brave Search."],
    ["google news", "Google's personalized news aggregation and search service."],
    ["qwant news", "News search and headlines from Qwant."],
    ["yahoo news", "News portal and search from Yahoo."],
    ["tagesschau (DE)", "German-language news search for Tagesschau, a major public broadcaster."]
  ],
  "videos": [
    ["bing videos", "Video search vertical from Microsoft Bing."],
    ["brave.videos", "Video search vertical of Brave Search."],
    ["duckduckgo videos", "Video search results from DuckDuckGo."],
    ["google videos", "Video-focused search results from Google."],
    ["qwant videos", "Video search vertical from Qwant."],
    ["bilibili", "Chinese video sharing and streaming platform popular for animation and games."],
    ["dailymotion", "Global video-sharing and hosting platform."],
    ["invidious", "Alternative, privacy-friendly front-end for YouTube content."],
    ["odysee", "Decentralized, blockchain-based video hosting platform."],
    ["peertube", "Federated, open source video hosting network."],
    ["piped", "Privacy-respecting alternative front-end for YouTube."],
    ["rumble", "Video sharing platform focusing on independent creators."],
    ["vimeo", "Ad-free video hosting platform used by filmmakers and businesses."],
    ["youtube", "The largest global video sharing and streaming platform."]
  ],
  "images": [
    ["bing images", "Image search engine by Microsoft Bing."],
    ["brave.images", "Image search vertical of Brave Search."],
    ["duckduckgo images", "Image search results from DuckDuckGo."],
    ["google images", "Google's dedicated image search service."],
    ["qwant images", "Image search vertical from Qwant."],
    ["deviantart", "Online community and gallery for digital art and illustrations."],
    ["flickr", "Image and short video hosting platform for photographers."],
    ["imgur", "Image hosting and sharing site popular for memes and galleries."],
    ["pinterest", "Visual discovery and bookmarking platform centered on images."],
    ["unsplash", "Library of freely usable, high-resolution photos."],
    ["wallhaven", "Community-driven wallpaper and background image repository."],
    ["wikicommons.images", "Image search across media stored on Wikimedia Commons."]
  ],
  "science": [
    ["arxiv", "Repository of preprint research papers in physics, math, CS and more."],
    ["crossref", "Infrastructure service providing DOIs and metadata for scholarly content."],
    ["google scholar", "Google's search engine for scholarly literature and citations."],
    ["internetarchivescholar", "Internet Archive search for digitized scholarly works."],
    ["pubmed", "Database of biomedical and life sciences literature from NCBI."],
    ["semantic scholar", "AI-powered literature search and discovery tool for research papers."]
  ],
  "it": [
    ["alpine linux packages", "Search index for Alpine Linux software packages."],
    ["crates.io", "Official package registry for Rust crates."],
    ["docker hub", "Central repository of Docker container images."],
    ["hex", "Package manager and repository for the Erlang and Elixir ecosystem."],
    ["hoogle", "API search engine for Haskell libraries and functions."],
    ["lib.rs", "Alternative index and front-end for Rust crates."],
    ["metacpan", "Search engine for Perl modules hosted on CPAN."],
    ["npm", "Package registry and manager for JavaScript and Node.js."],
    ["packagist", "Primary package repository for PHP Composer."],
    ["pkg.go.dev", "Documentation and discovery service for Go modules."],
    ["pub.dev", "Package repository for Dart and Flutter packages."],
    ["pypi", "Python Package Index, the main repository for Python packages."],
    ["rubygems", "Package manager and repository for Ruby gems."],
    ["voidlinux", "Package search for the Void Linux distribution."],
    ["askubuntu", "Q&A site focused on Ubuntu usage and troubleshooting."],
    ["stackoverflow", "Question-and-answer site for programmers and software development."],
    ["superuser", "Q&A site for advanced computer users and system administration."],
    ["bitbucket", "Git-based source code hosting and collaboration platform by Atlassian."],
    ["codeberg", "Non-profit, open source Git hosting platform."],
    ["gitea.com", "Hosted instance of the lightweight Gitea Git service."],
    ["github", "Popular Git-based code hosting and collaboration platform."],
    ["gitlab", "DevOps platform offering Git hosting, CI/CD, and project management."],
    ["sourcehut", "Minimalist suite of tools for software development and mailing lists."],
    ["arch linux wiki", "Extensive documentation wiki for Arch Linux and related tools."],
    ["gentoo", "Documentation wiki for the Gentoo Linux distribution."],
    ["mdn", "Mozilla Developer Network documentation for web technologies."],
    ["searchcode code", "Search engine indexing source code across public repositories."]
  ],
  "files": [
    ["library of congress", "Catalog and digital collections from the U.S. Library of Congress."],
    ["wikibooks", "Wikimedia project hosting free textbooks and manuals."],
    ["wikisource", "Wikimedia digital library of source texts and documents."],
    ["wikiversity", "Wikimedia project for educational resources and courses."],
    ["wikivoyage", "Free, community-created travel guide from Wikimedia."],
    ["google play movies", "Google's store for purchasing and renting movies and TV series."],
    ["mediathekviewweb (DE)", "Web interface to German public TV media libraries."],
    ["ina (FR)", "French National Audiovisual Institute archive search."],
    ["wikicommons.videos", "Search for video media stored on Wikimedia Commons."],
    ["wikicommons.audio", "Search for audio files stored on Wikimedia Commons."],
    ["apk mirror", "Repository for Android APK files outside official app stores."],
    ["apple app store", "Official iOS and iPadOS app distribution platform."],
    ["fdroid", "Catalog of free and open source Android applications."],
    ["google play apps", "Official Android app store operated by Google."]
  ],
  "social+media": [
    ["pinterest", "Visual discovery, bookmarking, and inspiration social platform."],
    ["reddit", "Social news aggregation and discussion website organized by communities."],
    ["9gag", "Humor-focused social media site for sharing memes and short posts."],
    ["lemmy posts", "Post search across Lemmy, a federated link-aggregation platform."]
  ],
  "map": [
    ["apple maps", "Apple's mapping and navigation service for its devices."],
    ["openstreetmap", "Collaborative, open data world map project."]
  ],
  "music": [
    ["genius", "Platform for song lyrics, annotations, and music commentary."],
    ["radio browser", "Directory and search engine for online radio stations."],
    ["bandcamp", "Music platform for independent artists to sell and stream releases."],
    ["deezer", "On-demand music streaming service."],
    ["mixcloud", "Streaming platform for DJ mixes, radio shows, and podcasts."],
    ["soundcloud", "Audio distribution and music sharing platform for creators."],
    ["youtube", "Video platform heavily used for streaming music and music videos."]
  ]
}
